# Server
server.port=8080
server.tomcat.uri-encoding=UTF-8
# Database
spring.datasource.url=jdbc:postgresql://postgres:5432/taskdb?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=postgres
spring.datasource.password=5141
spring.datasource.driver-class-name=org.postgresql.Driver
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
# Added database initialization
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:postgres/init.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.encoding=UTF-8
# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
# Kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=task-group
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# Logging
logging.level.com.demo.taskmanager=debug
logging.level.org.springframework.kafka=error
logging.logback.rollingpolicy.clean-history-on-start=true
logging.level.org.apache.kafka.clients.NetworkClient=error
logging.level.org.apache.kafka.server.quota=error
logging.level.org.apache.kafka.server.authorizer=error
logging.level.org.springframework.kafka.client=error
logging.level.org.springframework.kafka.broker=error
